import type { Language } from './translations'

export type SignType = 'mandatory' | 'prohibition' | 'warning' | 'emergency' | 'info'

export interface SafetyRule {
  id: string
  icon: string
  isoCode?: string
  signType: SignType
  category: 'ppe' | 'prohibition' | 'behavior' | 'emergency' | 'vehicle' | 'legal'
  label: Record<Language, string>
}

export function isoSignUrl(code: string) {
  return `https://commons.wikimedia.org/wiki/Special:FilePath/ISO_7010_${code}.svg`
}

// ISO 7010 color system
export const SIGN_STYLES: Record<SignType, { bg: string; border: string; text: string; shape: string; label: string }> = {
  mandatory:   { bg: 'bg-blue-600',   border: 'border-blue-700',  text: 'text-white',      shape: 'rounded-full', label: 'Gebot (blau)'       },
  prohibition: { bg: 'bg-red-600',    border: 'border-red-700',   text: 'text-white',      shape: 'rounded-full', label: 'Verbot (rot)'       },
  warning:     { bg: 'bg-yellow-400', border: 'border-yellow-500',text: 'text-slate-900',  shape: 'rounded',      label: 'Warnung (gelb)'     },
  emergency:   { bg: 'bg-green-600',  border: 'border-green-700', text: 'text-white',      shape: 'rounded-sm',   label: 'Rettung (grün)'     },
  info:        { bg: 'bg-slate-200',  border: 'border-slate-300', text: 'text-slate-700',  shape: 'rounded-sm',   label: 'Info (grau)'        },
}

export const SAFETY_RULE_CATEGORIES: Record<SafetyRule['category'], Record<Language, string>> = {
  ppe:        { de: 'Schutzausrüstung', en: 'Protective Equipment', pl: 'Środki ochrony', ro: 'Echipament de protecție', cs: 'Ochranné vybavení', hu: 'Védőfelszerelés', bg: 'Защитно оборудване', uk: 'Захисне спорядження', ru: 'Защитное снаряжение', tr: 'Koruyucu ekipman' },
  prohibition: { de: 'Verbote', en: 'Prohibitions', pl: 'Zakazy', ro: 'Interdicții', cs: 'Zákazy', hu: 'Tilalmak', bg: 'Забрани', uk: 'Заборони', ru: 'Запреты', tr: 'Yasaklar' },
  behavior:   { de: 'Verhaltensregeln', en: 'Conduct Rules', pl: 'Zasady zachowania', ro: 'Reguli de conduită', cs: 'Pravidla chování', hu: 'Magatartási szabályok', bg: 'Правила за поведение', uk: 'Правила поведінки', ru: 'Правила поведения', tr: 'Davranış kuralları' },
  emergency:  { de: 'Notfall & Sicherheit', en: 'Emergency & Safety', pl: 'Nagłe wypadki i bezpieczeństwo', ro: 'Urgențe și siguranță', cs: 'Nouzové situace a bezpečnost', hu: 'Vészhelyzet és biztonság', bg: 'Аварийни ситуации и безопасност', uk: 'Надзвичайні ситуації та безпека', ru: 'Аварийные ситуации и безопасность', tr: 'Acil durum ve güvenlik' },
  vehicle:    { de: 'Fahrzeug', en: 'Vehicle', pl: 'Pojazd', ro: 'Vehicul', cs: 'Vozidlo', hu: 'Jármű', bg: 'Превозно средство', uk: 'Транспортний засіб', ru: 'Транспортное средство', tr: 'Araç' },
  legal:      { de: 'Rechtliche Hinweise (DE)', en: 'Legal Notes (DE)', pl: 'Uwagi prawne (DE)', ro: 'Note juridice (DE)', cs: 'Právní poznámky (DE)', hu: 'Jogi megjegyzések (DE)', bg: 'Правни бележки (DE)', uk: 'Правові примітки (DE)', ru: 'Правовые примечания (DE)', tr: 'Hukuki notlar (DE)' },
}

export const SAFETY_RULES: SafetyRule[] = [
  // ── Schutzausrüstung ─────────────────────────────────────────────────────────
  {
    id: 'vest',
    icon: '🦺',
    isoCode: 'M015',
    signType: 'mandatory',
    category: 'ppe',
    label: {
      de: 'Warnweste und Sicherheitsschuhe tragen',
      en: 'Wear safety vest and safety shoes',
      pl: 'Nosić kamizelkę ostrzegawczą i obuwie ochronne',
      ro: 'Purtați vestă de siguranță și pantofi de protecție',
      cs: 'Noste reflexní vestu a bezpečnostní obuv',
      hu: 'Viseljen láthatósági mellényt és biztonsági cipőt',
      bg: 'Носете предупредителна жилетка и предпазни обувки',
      uk: 'Носіть сигнальний жилет і захисне взуття',
      ru: 'Носите сигнальный жилет и защитную обувь',
      tr: 'Uyarı yeleği ve güvenlik ayakkabısı giyin',
    },
  },
  {
    id: 'hard_hat',
    icon: '⛑️',
    isoCode: 'M014',
    signType: 'mandatory',
    category: 'ppe',
    label: {
      de: 'Schutzhelm tragen',
      en: 'Wear hard hat',
      pl: 'Nosić kask ochronny',
      ro: 'Purtați casca de protecție',
      cs: 'Noste ochrannou přilbu',
      hu: 'Viseljen védősisakot',
      bg: 'Носете защитна каска',
      uk: 'Носіть захисну каску',
      ru: 'Носите защитную каску',
      tr: 'Baret giyin',
    },
  },
  {
    id: 'safety_glasses',
    icon: '🥽',
    isoCode: 'M004',
    signType: 'mandatory',
    category: 'ppe',
    label: {
      de: 'Schutzbrille tragen',
      en: 'Wear safety glasses',
      pl: 'Nosić okulary ochronne',
      ro: 'Purtați ochelari de protecție',
      cs: 'Noste ochranné brýle',
      hu: 'Viseljen védőszemüveget',
      bg: 'Носете предпазни очила',
      uk: 'Носіть захисні окуляри',
      ru: 'Носите защитные очки',
      tr: 'Koruyucu gözlük takın',
    },
  },
  {
    id: 'gloves',
    icon: '🧤',
    isoCode: 'M009',
    signType: 'mandatory',
    category: 'ppe',
    label: {
      de: 'Schutzhandschuhe tragen',
      en: 'Wear protective gloves',
      pl: 'Nosić rękawice ochronne',
      ro: 'Purtați mănuși de protecție',
      cs: 'Noste ochranné rukavice',
      hu: 'Viseljen védőkesztyűt',
      bg: 'Носете предпазни ръкавици',
      uk: 'Носіть захисні рукавиці',
      ru: 'Носите защитные перчатки',
      tr: 'Koruyucu eldiven giyin',
    },
  },
  {
    id: 'ear_protection',
    icon: '🔇',
    isoCode: 'M003',
    signType: 'mandatory',
    category: 'ppe',
    label: {
      de: 'Gehörschutz tragen',
      en: 'Wear ear protection',
      pl: 'Nosić ochronniki słuchu',
      ro: 'Purtați protecție auditivă',
      cs: 'Noste chrániče sluchu',
      hu: 'Viseljen hallásvédelmet',
      bg: 'Носете предпазни слушалки',
      uk: 'Носіть засоби захисту слуху',
      ru: 'Носите средства защиты слуха',
      tr: 'Kulak koruyucu takın',
    },
  },

  // ── Verbote ──────────────────────────────────────────────────────────────────
  {
    id: 'no_smoking',
    icon: '🚭',
    isoCode: 'P002',
    signType: 'prohibition',
    category: 'prohibition',
    label: {
      de: 'Rauchen verboten',
      en: 'No smoking',
      pl: 'Palenie wzbronione',
      ro: 'Fumatul interzis',
      cs: 'Zákaz kouření',
      hu: 'Tilos a dohányzás',
      bg: 'Забранено пушенето',
      uk: 'Куріння заборонено',
      ru: 'Курение запрещено',
      tr: 'Sigara içmek yasaktır',
    },
  },
  {
    id: 'no_open_fire',
    icon: '🔥',
    isoCode: 'P003',
    signType: 'prohibition',
    category: 'prohibition',
    label: {
      de: 'Offenes Feuer und Funkenbildung verboten',
      en: 'No open fire or sparks',
      pl: 'Zakaz otwartego ognia i iskrzenia',
      ro: 'Foc deschis și scântei interzise',
      cs: 'Otevřený oheň a jiskření zakázáno',
      hu: 'Nyílt láng és szikraképzés tilos',
      bg: 'Открит огън и искри забранени',
      uk: 'Відкритий вогонь та іскроутворення заборонені',
      ru: 'Открытый огонь и искрообразование запрещены',
      tr: 'Açık ateş ve kıvılcım yasaktır',
    },
  },
  {
    id: 'no_alcohol',
    icon: '🍺',
    isoCode: 'P005',
    signType: 'prohibition',
    category: 'prohibition',
    label: {
      de: 'Alkohol- und Drogenverbot auf dem Betriebsgelände',
      en: 'Alcohol and drugs prohibited on premises',
      pl: 'Zakaz alkoholu i narkotyków na terenie zakładu',
      ro: 'Alcoolul și drogurile sunt interzise pe teritoriu',
      cs: 'Alkohol a drogy v areálu zakázány',
      hu: 'Alkohol és kábítószer tilos a telephely területén',
      bg: 'Алкохол и наркотици забранени на територията',
      uk: 'Алкоголь та наркотики заборонені на території',
      ru: 'Алкоголь и наркотики запрещены на территории',
      tr: 'Tesis alanında alkol ve uyuşturucu yasaktır',
    },
  },
  {
    id: 'no_phone',
    icon: '📵',
    isoCode: 'P013',
    signType: 'prohibition',
    category: 'prohibition',
    label: {
      de: 'Handynutzung während der Fahrt verboten',
      en: 'Mobile phone use while driving prohibited',
      pl: 'Zakaz używania telefonu podczas jazdy',
      ro: 'Utilizarea telefonului în timpul conducerii interzisă',
      cs: 'Používání telefonu za jízdy zakázáno',
      hu: 'Mobiltelefon használata vezetés közben tilos',
      bg: 'Забранено използването на телефон по време на шофиране',
      uk: 'Використання телефону під час керування забороненое',
      ru: 'Использование телефона во время езды запрещено',
      tr: 'Sürüş sırasında cep telefonu kullanımı yasaktır',
    },
  },
  {
    id: 'no_entry',
    icon: '🔒',
    isoCode: 'P004',
    signType: 'prohibition',
    category: 'prohibition',
    label: {
      de: 'Lagerhallen und Produktion: Zutritt verboten',
      en: 'No entry to warehouse and production areas',
      pl: 'Magazyny i produkcja: wstęp wzbroniony',
      ro: 'Depozit și producție: accesul interzis',
      cs: 'Sklady a výroba: vstup zakázán',
      hu: 'Raktár és gyártás: belépés tilos',
      bg: 'Складове и производство: забранен достъп',
      uk: 'Склади та виробництво: вхід заборонено',
      ru: 'Склады и производство: вход запрещён',
      tr: 'Depo ve üretim alanlarına giriş yasaktır',
    },
  },
  {
    id: 'no_headphones',
    icon: '🎧',
    signType: 'prohibition',
    category: 'prohibition',
    label: {
      de: 'Kopfhörer tragen und Fotografieren verboten',
      en: 'Headphones and photography prohibited',
      pl: 'Słuchawki i fotografowanie zabronione',
      ro: 'Căști și fotografierea interzise',
      cs: 'Sluchátka a fotografování zakázáno',
      hu: 'Fejhallgató és fényképezés tilos',
      bg: 'Слушалки и фотографиране забранени',
      uk: 'Навушники та фотографування заборонені',
      ru: 'Наушники и фотографирование запрещены',
      tr: 'Kulaklık ve fotoğraf çekimi yasaktır',
    },
  },
  {
    id: 'no_overnight',
    icon: '🛌',
    signType: 'prohibition',
    category: 'prohibition',
    label: {
      de: 'Übernachten auf dem Betriebsgelände verboten',
      en: 'Overnight stay on company premises prohibited',
      pl: 'Nocowanie na terenie zakładu zabronione',
      ro: 'Înnoptarea pe teritoriul întreprinderii interzisă',
      cs: 'Nocování v areálu zakázáno',
      hu: 'Éjszakázás a telephelyen tilos',
      bg: 'Нощуване на територията на предприятието забранено',
      uk: 'Ночівля на території підприємства заборонена',
      ru: 'Ночёвка на территории предприятия запрещена',
      tr: 'Tesis alanında geceleme yasaktır',
    },
  },

  // ── Verhaltensregeln ─────────────────────────────────────────────────────────
  {
    id: 'forklift',
    icon: '⚠️',
    isoCode: 'W014',
    signType: 'warning',
    category: 'behavior',
    label: {
      de: 'Achtung Staplerverkehr',
      en: 'Caution – forklift traffic',
      pl: 'Uwaga – ruch wózków widłowych',
      ro: 'Atenție – trafic cu stivuitoare',
      cs: 'Pozor – provoz vysokozdvižných vozíků',
      hu: 'Figyelem – targonca-forgalom',
      bg: 'Внимание – движение на мотокари',
      uk: 'Увага – рух навантажувачів',
      ru: 'Внимание – движение погрузчиков',
      tr: 'Dikkat – forklift trafiği',
    },
  },
  {
    id: 'stay_vehicle',
    icon: '🚛',
    isoCode: 'M001',
    signType: 'mandatory',
    category: 'behavior',
    label: {
      de: 'Am Fahrzeug bleiben und Anweisungen beachten',
      en: 'Stay by the vehicle and follow instructions',
      pl: 'Pozostać przy pojeździe i stosować się do poleceń',
      ro: 'Rămâneți lângă vehicul și urmați instrucțiunile',
      cs: 'Zůstaňte u vozidla a dodržujte pokyny',
      hu: 'Maradjon a járműnél és kövesse az utasításokat',
      bg: 'Оставайте при превозното средство и следвайте указанията',
      uk: 'Залишайтеся біля транспорту та виконуйте вказівки',
      ru: 'Оставайтесь у транспорта и выполняйте указания',
      tr: 'Araçta kalın ve talimatlara uyun',
    },
  },
  {
    id: 'speed_limit',
    icon: '🚶',
    signType: 'warning',
    category: 'behavior',
    label: {
      de: 'Schrittgeschwindigkeit auf dem Betriebsgelände (5 km/h)',
      en: 'Walking pace on company premises (5 km/h)',
      pl: 'Prędkość kroków na terenie zakładu (5 km/h)',
      ro: 'Viteză de mers pe jos pe teritoriul întreprinderii (5 km/h)',
      cs: 'Rychlost chůze v areálu (5 km/h)',
      hu: 'Lépési sebesség a telephely területén (5 km/h)',
      bg: 'Скорост на крачка на територията на предприятието (5 км/ч)',
      uk: 'Крокова швидкість на території підприємства (5 км/год)',
      ru: 'Скорость шага на территории предприятия (5 км/ч)',
      tr: 'Tesis alanında yürüyüş hızı (5 km/s)',
    },
  },
  {
    id: 'designated_paths',
    icon: '🛤️',
    isoCode: 'M001',
    signType: 'mandatory',
    category: 'behavior',
    label: {
      de: 'Nur auf ausgewiesenen Wegen und Flächen bewegen',
      en: 'Use designated paths and areas only',
      pl: 'Poruszać się tylko po wyznaczonych drogach i obszarach',
      ro: 'Folosiți numai căile și zonele desemnate',
      cs: 'Pohybujte se pouze po vyznačených cestách a plochách',
      hu: 'Csak a kijelölt utakon és területeken közlekedjen',
      bg: 'Движете се само по обозначените пътища и площадки',
      uk: 'Рухайтеся лише позначеними маршрутами та площадками',
      ru: 'Передвигайтесь только по обозначенным путям и площадкам',
      tr: 'Yalnızca belirlenmiş yolları ve alanları kullanın',
    },
  },
  {
    id: 'keep_clear',
    icon: '↔️',
    isoCode: 'M001',
    signType: 'mandatory',
    category: 'behavior',
    label: {
      de: 'Haupteinfahrt freihalten',
      en: 'Keep the main entrance clear',
      pl: 'Utrzymać wolny główny wjazd',
      ro: 'Mențineți intrarea principală liberă',
      cs: 'Udržujte hlavní vjezd volný',
      hu: 'A főbejáratot tartsa szabadon',
      bg: 'Дръжте главния вход свободен',
      uk: 'Тримайте головний в\'їзд вільним',
      ru: 'Держите главный въезд свободным',
      tr: 'Ana girişi açık tutun',
    },
  },
  {
    id: 'doors_closed',
    icon: '🚪',
    isoCode: 'M001',
    signType: 'mandatory',
    category: 'behavior',
    label: {
      de: 'Tore und Türen stets geschlossen halten',
      en: 'Keep gates and doors closed at all times',
      pl: 'Zawsze trzymać bramy i drzwi zamknięte',
      ro: 'Mențineți porțile și ușile închise în permanență',
      cs: 'Vždy udržujte vrata a dveře zavřená',
      hu: 'A kapukat és ajtókat mindig tartsa zárva',
      bg: 'Дръжте портите и вратите затворени по всяко време',
      uk: 'Тримайте ворота та двері постійно зачиненими',
      ru: 'Держите ворота и двери постоянно закрытыми',
      tr: 'Kapı ve kapakları her zaman kapalı tutun',
    },
  },
  {
    id: 'cctv',
    icon: '📹',
    signType: 'info',
    category: 'behavior',
    label: {
      de: 'Videoüberwachung auf dem Betriebsgelände',
      en: 'Video surveillance on company premises',
      pl: 'Monitoring wideo na terenie zakładu',
      ro: 'Supraveghere video pe teritoriul întreprinderii',
      cs: 'Kamerový systém v areálu',
      hu: 'Videó megfigyelés a telephelyen',
      bg: 'Видеонаблюдение на територията на предприятието',
      uk: 'Відеоспостереження на території підприємства',
      ru: 'Видеонаблюдение на территории предприятия',
      tr: 'Tesis alanında video gözetimi',
    },
  },
  {
    id: 'winter',
    icon: '❄️',
    isoCode: 'W011',
    signType: 'warning',
    category: 'behavior',
    label: {
      de: 'Bei Schnee/Eisglätte: Räumdienst abwarten',
      en: 'In case of snow/ice: wait for clearance service',
      pl: 'Przy śniegu/oblodzeniu: czekać na służby odśnieżające',
      ro: 'În caz de zăpadă/gheață: așteptați serviciul de deszăpezire',
      cs: 'Při sněhu/náledí: vyčkejte na úklidovou službu',
      hu: 'Hó/jég esetén: várja meg a takarítószolgálatot',
      bg: 'При сняг/лед: изчакайте службата за почистване',
      uk: 'При снігу/ожеледиці: зачекайте на службу прибирання',
      ru: 'При снеге/гололёде: дождитесь уборочной службы',
      tr: 'Kar/buz durumunda: temizleme servisini bekleyin',
    },
  },
  {
    id: 'waste',
    icon: '🗑️',
    isoCode: 'M001',
    signType: 'mandatory',
    category: 'behavior',
    label: {
      de: 'Abfall ordnungsgemäß entsorgen',
      en: 'Dispose of waste properly',
      pl: 'Odpady utylizować zgodnie z przepisami',
      ro: 'Eliminați deșeurile în mod corespunzător',
      cs: 'Odpad řádně likvidujte',
      hu: 'A hulladékot megfelelően ártalmatlanítsa',
      bg: 'Изхвърляйте отпадъците правилно',
      uk: 'Утилізуйте відходи належним чином',
      ru: 'Утилизируйте отходы надлежащим образом',
      tr: 'Atıkları uygun şekilde imha edin',
    },
  },

  // ── Fahrzeug ─────────────────────────────────────────────────────────────────
  {
    id: 'engine_off',
    icon: '🔑',
    isoCode: 'M021',
    signType: 'mandatory',
    category: 'vehicle',
    label: {
      de: 'Motor abstellen beim Be- und Entladen',
      en: 'Switch off engine during loading and unloading',
      pl: 'Wyłączyć silnik podczas załadunku i rozładunku',
      ro: 'Opriți motorul în timpul încărcării și descărcării',
      cs: 'Při nakládání a vykládání vypněte motor',
      hu: 'Rakodás közben kapcsolja ki a motort',
      bg: 'Изключете двигателя при товарене и разтоварване',
      uk: 'Вимикайте двигун під час завантаження та розвантаження',
      ru: 'Глушите двигатель при погрузке и разгрузке',
      tr: 'Yükleme ve boşaltma sırasında motoru kapatın',
    },
  },
  {
    id: 'handbrake',
    icon: '✋',
    isoCode: 'M001',
    signType: 'mandatory',
    category: 'vehicle',
    label: {
      de: 'Handbremse anziehen und Fahrzeug sichern',
      en: 'Apply handbrake and secure vehicle',
      pl: 'Zaciągnąć hamulec ręczny i zabezpieczyć pojazd',
      ro: 'Trageți frâna de mână și asigurați vehiculul',
      cs: 'Zatáhněte ruční brzdu a zajistěte vozidlo',
      hu: 'Húzza fel a kéziféket és rögzítse a járművet',
      bg: 'Задействайте ръчната спирачка и обезопасете превозното средство',
      uk: 'Затягніть ручне гальмо та зафіксуйте транспортний засіб',
      ru: 'Затяните ручной тормоз и зафиксируйте транспортное средство',
      tr: 'El frenini çekin ve aracı güvenceye alın',
    },
  },
  {
    id: 'chocks',
    icon: '⬛',
    isoCode: 'M001',
    signType: 'mandatory',
    category: 'vehicle',
    label: {
      de: 'Unterlegkeile vor und hinter den Rädern verwenden',
      en: 'Use wheel chocks in front of and behind wheels',
      pl: 'Stosować kliny pod koła przed i za kołami',
      ro: 'Folosiți calele de roată în fața și în spatele roților',
      cs: 'Používejte klíny před a za kola',
      hu: 'Kerékklincseket használjon a kerekek elé és mögé',
      bg: 'Използвайте клинове пред и зад колелата',
      uk: 'Використовуйте противідкатні клини перед та позаду коліс',
      ru: 'Используйте противооткатные упоры перед и за колёсами',
      tr: 'Tekerleklerin önüne ve arkasına takoz koyun',
    },
  },
  {
    id: 'seatbelt',
    icon: '🔒',
    isoCode: 'M012',
    signType: 'mandatory',
    category: 'vehicle',
    label: {
      de: 'Sicherheitsgurt anlegen',
      en: 'Fasten seatbelt',
      pl: 'Zapiąć pas bezpieczeństwa',
      ro: 'Puneți centura de siguranță',
      cs: 'Zapněte bezpečnostní pás',
      hu: 'Csatolja be a biztonsági övet',
      bg: 'Поставете предпазния колан',
      uk: 'Застебніть ремінь безпеки',
      ru: 'Пристегните ремень безопасности',
      tr: 'Emniyet kemerini takın',
    },
  },
  {
    id: 'load_securing',
    icon: '📦',
    isoCode: 'M001',
    signType: 'mandatory',
    category: 'vehicle',
    label: {
      de: 'Ladungssicherung vor Abfahrt prüfen',
      en: 'Check load securing before departure',
      pl: 'Sprawdzić mocowanie ładunku przed odjazdem',
      ro: 'Verificați fixarea încărcăturii înainte de plecare',
      cs: 'Před odjezdem zkontrolujte zajištění nákladu',
      hu: 'Indulás előtt ellenőrizze a rakomány rögzítését',
      bg: 'Проверете закрепването на товара преди тръгване',
      uk: 'Перевірте кріплення вантажу перед відправленням',
      ru: 'Проверьте крепление груза перед отправкой',
      tr: 'Hareket etmeden önce yük sabitlemeyi kontrol edin',
    },
  },

  // ── Notfall & Sicherheit ──────────────────────────────────────────────────────
  {
    id: 'emergency_exit',
    icon: '🚨',
    isoCode: 'E001',
    signType: 'emergency',
    category: 'emergency',
    label: {
      de: 'Notausgänge und Fluchtwege freihalten',
      en: 'Keep emergency exits and escape routes clear',
      pl: 'Utrzymywać wolne wyjścia awaryjne i drogi ewakuacyjne',
      ro: 'Mențineți libere ieșirile de urgență și căile de evacuare',
      cs: 'Udržujte volné nouzové východy a únikové cesty',
      hu: 'Tartsa szabadon a vészkijáratokat és menekülési útvonalakat',
      bg: 'Дръжте аварийните изходи и пътищата за евакуация свободни',
      uk: 'Тримайте аварійні виходи та шляхи евакуації вільними',
      ru: 'Держите аварийные выходы и пути эвакуации свободными',
      tr: 'Acil çıkışları ve kaçış yollarını açık tutun',
    },
  },
  {
    id: 'first_aid',
    icon: '🩺',
    isoCode: 'E003',
    signType: 'emergency',
    category: 'emergency',
    label: {
      de: 'Standort des Erste-Hilfe-Kastens kennen',
      en: 'Know the location of the first aid kit',
      pl: 'Znać lokalizację apteczki pierwszej pomocy',
      ro: 'Cunoașteți locația trusii de prim ajutor',
      cs: 'Znáte umístění lékárničky první pomoci',
      hu: 'Ismerje az elsősegély-készlet helyét',
      bg: 'Познайте местоположението на аптечката за първа помощ',
      uk: 'Знайте місце розташування аптечки першої допомоги',
      ru: 'Знайте местонахождение аптечки первой помощи',
      tr: 'İlk yardım çantasının yerini bilin',
    },
  },
  {
    id: 'fire_extinguisher',
    icon: '🧯',
    isoCode: 'F001',
    signType: 'emergency',
    category: 'emergency',
    label: {
      de: 'Standort der Feuerlöscher kennen',
      en: 'Know the location of fire extinguishers',
      pl: 'Znać lokalizację gaśnic',
      ro: 'Cunoașteți locația stingătoarelor de incendiu',
      cs: 'Znáte umístění hasicích přístrojů',
      hu: 'Ismerje a tűzoltó készülékek helyét',
      bg: 'Познайте местоположението на пожарогасителите',
      uk: 'Знайте місце розташування вогнегасників',
      ru: 'Знайте местонахождение огнетушителей',
      tr: 'Yangın söndürücülerin yerini bilin',
    },
  },
  {
    id: 'report_hazards',
    icon: '📋',
    isoCode: 'E004',
    signType: 'emergency',
    category: 'emergency',
    label: {
      de: 'Gefahren und Unfälle sofort melden',
      en: 'Report hazards and accidents immediately',
      pl: 'Natychmiast zgłaszać zagrożenia i wypadki',
      ro: 'Raportați imediat pericolele și accidentele',
      cs: 'Nebezpečí a nehody ihned hlaste',
      hu: 'A veszélyeket és baleseteket azonnal jelentse',
      bg: 'Незабавно докладвайте за опасности и злополуки',
      uk: 'Негайно повідомляйте про небезпеки та нещасні випадки',
      ru: 'Немедленно сообщайте об опасностях и несчастных случаях',
      tr: 'Tehlikeleri ve kazaları derhal bildirin',
    },
  },

  // ── Rechtliche Hinweise (DE) ─────────────────────────────────────────────────
  {
    id: 'loading_dock',
    icon: '🏗️',
    isoCode: 'W015',
    signType: 'warning',
    category: 'legal',
    label: {
      de: 'Laderampe nur mit Einweisung durch Personal benutzen (DGUV Vorschrift 70)',
      en: 'Use loading dock only with staff instruction (DGUV Regulation 70)',
      pl: 'Rampa załadowcza tylko z instruktażem personelu (DGUV Przepis 70)',
      ro: 'Utilizați rampa de încărcare numai cu instrucțiunile personalului (DGUV Reg. 70)',
      cs: 'Nakládací rampu používejte pouze s instrukcí personálu (DGUV Předpis 70)',
      hu: 'A rakodórámpát csak a személyzet útmutatásával használja (DGUV 70. előírás)',
      bg: 'Товарна рампа само с инструктаж на персонала (DGUV Наредба 70)',
      uk: 'Вантажна рампа лише з інструктажем персоналу (DGUV Приписи 70)',
      ru: 'Погрузочная рампа только с инструктажем персонала (DGUV Предписание 70)',
      tr: 'Yükleme rampasını yalnızca personel talimatıyla kullanın (DGUV Yönetmelik 70)',
    },
  },
  {
    id: 'adr_hazmat',
    icon: '☢️',
    isoCode: 'W016',
    signType: 'warning',
    category: 'legal',
    label: {
      de: 'Gefahrgut-Kennzeichnung (ADR) beachten und Begleitpapiere bereithalten',
      en: 'Observe hazardous goods markings (ADR) and keep documents ready',
      pl: 'Przestrzegać oznakowania towarów niebezpiecznych (ADR) i trzymać dokumenty',
      ro: 'Respectați marcajele mărfurilor periculoase (ADR) și păstrați documentele',
      cs: 'Dodržujte označení nebezpečného zboží (ADR) a mějte doklady připravené',
      hu: 'Tartsa be a veszélyes áruk jelöléseit (ADR) és tartsa kéznél a dokumentumokat',
      bg: 'Спазвайте маркировката на опасните стоки (ADR) и дръжте документите готови',
      uk: 'Дотримуйтеся маркування небезпечних вантажів (ADR) та тримайте документи',
      ru: 'Соблюдайте маркировку опасных грузов (ADR) и держите документы наготове',
      tr: 'Tehlikeli mal işaretlerine (ADR) uyun ve belgeleri hazır bulundurun',
    },
  },
  {
    id: 'no_pressure_vessels',
    icon: '⚗️',
    isoCode: 'P012',
    signType: 'prohibition',
    category: 'legal',
    label: {
      de: 'Druckbehälter und Gasflaschen nur mit Genehmigung auf das Gelände (BetrSichV)',
      en: 'Pressure vessels and gas cylinders on premises only with authorization (BetrSichV)',
      pl: 'Zbiorniki ciśnieniowe i butle gazowe tylko za zezwoleniem (BetrSichV)',
      ro: 'Recipiente sub presiune și butelii de gaz pe teritoriu numai cu autorizație (BetrSichV)',
      cs: 'Tlakové nádoby a plynové láhve v areálu pouze s povolením (BetrSichV)',
      hu: 'Nyomástartó edények és gázpalackok csak engedéllyel a területen (BetrSichV)',
      bg: 'Съдове под налягане и газови бутилки само с разрешение (BetrSichV)',
      uk: 'Посудини під тиском та газові балони лише з дозволом (BetrSichV)',
      ru: 'Сосуды под давлением и газовые баллоны только с разрешением (BetrSichV)',
      tr: 'Basınçlı kaplar ve gaz tüpleri tesise yalnızca izinle (BetrSichV)',
    },
  },
  {
    id: 'legal_instruction',
    icon: '⚖️',
    signType: 'info',
    category: 'legal',
    label: {
      de: 'Diese Unterweisung gilt als Sicherheitsunterweisung gemäß §12 ArbSchG',
      en: 'This briefing constitutes a safety instruction pursuant to §12 ArbSchG',
      pl: 'Ten instruktaż jest instruktażem bezpieczeństwa zgodnie z §12 ArbSchG',
      ro: 'Acest instructaj constituie instructaj de securitate conform §12 ArbSchG',
      cs: 'Toto školení platí jako bezpečnostní školení dle §12 ArbSchG',
      hu: 'Ez az oktatás biztonsági oktatásnak minősül a §12 ArbSchG szerint',
      bg: 'Този инструктаж е инструктаж по безопасност съгласно §12 ArbSchG',
      uk: 'Цей інструктаж є інструктажем з безпеки відповідно до §12 ArbSchG',
      ru: 'Данный инструктаж является инструктажем по безопасности согласно §12 ArbSchG',
      tr: 'Bu brifing, §12 ArbSchG uyarınca güvenlik eğitimi olarak geçerlidir',
    },
  },
]
