import type { Language } from './translations'

export interface SafetyRule {
  id: string
  icon: string
  label: Record<Language, string>
}

export const SAFETY_RULES: SafetyRule[] = [
  {
    id: 'vest',
    icon: '🦺',
    label: {
      de: 'Warnweste und Sicherheitsschuhe tragen',
      en: 'Wear safety vest and safety shoes',
      pl: 'Nosić kamizelkę ostrzegawczą i obuwie ochronne',
      ro: 'Purtați vestă de siguranță și pantofi de protecție',
      cs: 'Noste reflexní vestu a bezpečnostní obuv',
      hu: 'Viseljen láthatósági mellényt és biztonsági cipőt',
      bg: 'Носете предупредителна жилетка и предпазни обувки',
      uk: 'Носіть сигнальний жилет і захисне взуття',
      ru: 'Носите сигнальный жилет и защитную обувь',
      tr: 'Uyarı yeleği ve güvenlik ayakkabısı giyin',
    },
  },
  {
    id: 'forklift',
    icon: '⚠️',
    label: {
      de: 'Achtung Staplerverkehr',
      en: 'Caution – forklift traffic',
      pl: 'Uwaga – ruch wózków widłowych',
      ro: 'Atenție – trafic cu stivuitoare',
      cs: 'Pozor – provoz vysokozdvižných vozíků',
      hu: 'Figyelem – targonca-forgalom',
      bg: 'Внимание – движение на мотокари',
      uk: 'Увага – рух навантажувачів',
      ru: 'Внимание – движение погрузчиков',
      tr: 'Dikkat – forklift trafiği',
    },
  },
  {
    id: 'no_entry',
    icon: '🚫',
    label: {
      de: 'Lagerhallen und Produktion: Zutritt verboten',
      en: 'No entry to warehouse and production areas',
      pl: 'Magazyny i produkcja: wstęp wzbroniony',
      ro: 'Depozit și producție: accesul interzis',
      cs: 'Sklady a výroba: vstup zakázán',
      hu: 'Raktár és gyártás: belépés tilos',
      bg: 'Складове и производство: забранен достъп',
      uk: 'Склади та виробництво: вхід заборонено',
      ru: 'Склады и производство: вход запрещён',
      tr: 'Depo ve üretim alanlarına giriş yasaktır',
    },
  },
  {
    id: 'stay_vehicle',
    icon: '🚛',
    label: {
      de: 'Am Fahrzeug bleiben und Anweisungen beachten',
      en: 'Stay by the vehicle and follow instructions',
      pl: 'Pozostać przy pojeździe i stosować się do poleceń',
      ro: 'Rămâneți lângă vehicul și urmați instrucțiunile',
      cs: 'Zůstaňte u vozidla a dodržujte pokyny',
      hu: 'Maradjon a járműnél és kövesse az utasításokat',
      bg: 'Оставайте при превозното средство и следвайте указанията',
      uk: 'Залишайтеся біля транспорту та виконуйте вказівки',
      ru: 'Оставайтесь у транспорта и выполняйте указания',
      tr: 'Araçta kalın ve talimatlara uyun',
    },
  },
  {
    id: 'speed_limit',
    icon: '🚶',
    label: {
      de: 'Schrittgeschwindigkeit auf dem Betriebsgelände (5 km/h)',
      en: 'Walking pace on company premises (5 km/h)',
      pl: 'Prędkość kroków na terenie zakładu (5 km/h)',
      ro: 'Viteză de mers pe jos pe teritoriul întreprinderii (5 km/h)',
      cs: 'Rychlost chůze v areálu (5 km/h)',
      hu: 'Lépési sebesség a telephely területén (5 km/h)',
      bg: 'Скорост на крачка на територията на предприятието (5 км/ч)',
      uk: 'Крокова швидкість на території підприємства (5 км/год)',
      ru: 'Скорость шага на территории предприятия (5 км/ч)',
      tr: 'Tesis alanında yürüyüş hızı (5 km/s)',
    },
  },
  {
    id: 'no_headphones',
    icon: '🎧',
    label: {
      de: 'Kopfhörer tragen und Fotografieren verboten',
      en: 'Headphones and photography prohibited',
      pl: 'Słuchawki i fotografowanie zabronione',
      ro: 'Căști și fotografierea interzise',
      cs: 'Sluchátka a fotografování zakázáno',
      hu: 'Fejhallgató és fényképezés tilos',
      bg: 'Слушалки и фотографиране забранени',
      uk: 'Навушники та фотографування заборонені',
      ru: 'Наушники и фотографирование запрещены',
      tr: 'Kulaklık ve fotoğraf çekimi yasaktır',
    },
  },
  {
    id: 'no_overnight',
    icon: '🌙',
    label: {
      de: 'Übernachten auf dem Betriebsgelände verboten',
      en: 'Overnight stay on company premises prohibited',
      pl: 'Nocowanie na terenie zakładu zabronione',
      ro: 'Înnoptarea pe teritoriul întreprinderii interzisă',
      cs: 'Nocování v areálu zakázáno',
      hu: 'Éjszakázás a telephelyen tilos',
      bg: 'Нощуване на територията на предприятието забранено',
      uk: 'Ночівля на території підприємства заборонена',
      ru: 'Ночёвка на территории предприятия запрещена',
      tr: 'Tesis alanında geceleme yasaktır',
    },
  },
  {
    id: 'keep_clear',
    icon: '🚧',
    label: {
      de: 'Haupteinfahrt freihalten',
      en: 'Keep the main entrance clear',
      pl: 'Utrzymać wolny główny wjazd',
      ro: 'Mențineți intrarea principală liberă',
      cs: 'Udržujte hlavní vjezd volný',
      hu: 'A főbejáratot tartsa szabadon',
      bg: 'Дръжте главния вход свободен',
      uk: 'Тримайте головний в\'їзд вільним',
      ru: 'Держите главный въезд свободным',
      tr: 'Ana girişi açık tutun',
    },
  },
  {
    id: 'cctv',
    icon: '📹',
    label: {
      de: 'Videoüberwachung auf dem Betriebsgelände',
      en: 'Video surveillance on company premises',
      pl: 'Monitoring wideo na terenie zakładu',
      ro: 'Supraveghere video pe teritoriul întreprinderii',
      cs: 'Kamerový systém v areálu',
      hu: 'Videó megfigyelés a telephelyen',
      bg: 'Видеонаблюдение на територията на предприятието',
      uk: 'Відеоспостереження на території підприємства',
      ru: 'Видеонаблюдение на территории предприятия',
      tr: 'Tesis alanında video gözetimi',
    },
  },
  {
    id: 'winter',
    icon: '❄️',
    label: {
      de: 'Bei Schnee/Eisglätte: Räumdienst abwarten',
      en: 'In case of snow/ice: wait for clearance service',
      pl: 'Przy śniegu/oblodzeniu: czekać na służby odśnieżające',
      ro: 'În caz de zăpadă/gheață: așteptați serviciul de deszăpezire',
      cs: 'Při sněhu/náledí: vyčkejte na úklidovou službu',
      hu: 'Hó/jég esetén: várja meg a takarítószolgálatot',
      bg: 'При сняг/лед: изчакайте службата за почистване',
      uk: 'При снігу/ожеледиці: зачекайте на службу прибирання',
      ru: 'При снеге/гололёде: дождитесь уборочной службы',
      tr: 'Kar/buz durumunda: temizleme servisini bekleyin',
    },
  },
]
