import { createEnv } from '@t3-oss/env-nextjs'
import { z } from 'zod'

export const env = createEnv({
  server: {
    SUPABASE_SERVICE_ROLE_KEY: z.string().min(1),
    BREVO_API_KEY: z.string().min(1),
    DIGEST_FROM_EMAIL: z.string().email(),
    APP_URL: z.string().url(),
    CRON_SECRET: z.string().min(1),
    SUPERADMIN_PASSWORD: z.string().min(1),
    SITE_PASSWORD: z.string().optional(),
    DEEPL_API_KEY: z.string().optional(),
    SENTRY_DSN: z.string().url().optional(),
    SENTRY_ORG: z.string().optional(),
    SENTRY_PROJECT: z.string().optional(),
    STRIPE_SECRET_KEY: z.string().startsWith('sk_').optional(),
    STRIPE_WEBHOOK_SECRET: z.string().startsWith('whsec_').optional(),
    // Legacy-Prices (Modell 49/99/500) — bleiben für Beta-Kunden als Fallback
    STRIPE_PRICE_STARTER: z.string().startsWith('price_').optional(),
    STRIPE_PRICE_PROFESSIONAL: z.string().startsWith('price_').optional(),
    STRIPE_PRICE_ENTERPRISE: z.string().startsWith('price_').optional(),
    // Neues Modell (Solo/Business/Enterprise, M+Y)
    STRIPE_PRICE_SOLO_MONTHLY: z.string().startsWith('price_').optional(),
    STRIPE_PRICE_SOLO_YEARLY: z.string().startsWith('price_').optional(),
    STRIPE_PRICE_BUSINESS_MONTHLY: z.string().startsWith('price_').optional(),
    STRIPE_PRICE_BUSINESS_YEARLY: z.string().startsWith('price_').optional(),
    STRIPE_PRICE_ENTERPRISE_MONTHLY: z.string().startsWith('price_').optional(),
    STRIPE_PRICE_ENTERPRISE_YEARLY: z.string().startsWith('price_').optional(),
    // Add-ons (6 aktiv, jeweils M+Y)
    STRIPE_PRICE_ADDON_PRINTER_MONTHLY: z.string().startsWith('price_').optional(),
    STRIPE_PRICE_ADDON_PRINTER_YEARLY: z.string().startsWith('price_').optional(),
    STRIPE_PRICE_ADDON_PRINTER_HARDWARE: z.string().startsWith('price_').optional(),
    STRIPE_PRICE_ADDON_AUDIT_EXPORT_MONTHLY: z.string().startsWith('price_').optional(),
    STRIPE_PRICE_ADDON_AUDIT_EXPORT_YEARLY: z.string().startsWith('price_').optional(),
    STRIPE_PRICE_ADDON_CUSTOM_BRANDING_MONTHLY: z.string().startsWith('price_').optional(),
    STRIPE_PRICE_ADDON_CUSTOM_BRANDING_YEARLY: z.string().startsWith('price_').optional(),
    STRIPE_PRICE_ADDON_EXTRA_LOCATION_MONTHLY: z.string().startsWith('price_').optional(),
    STRIPE_PRICE_ADDON_EXTRA_LOCATION_YEARLY: z.string().startsWith('price_').optional(),
    STRIPE_PRICE_ADDON_BRIEFING_TRANSLATION_MONTHLY: z.string().startsWith('price_').optional(),
    STRIPE_PRICE_ADDON_BRIEFING_TRANSLATION_YEARLY: z.string().startsWith('price_').optional(),
    STRIPE_PRICE_ADDON_PRIORITY_SUPPORT_MONTHLY: z.string().startsWith('price_').optional(),
    STRIPE_PRICE_ADDON_PRIORITY_SUPPORT_YEARLY: z.string().startsWith('price_').optional(),
    NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  },
  client: {
    NEXT_PUBLIC_SUPABASE_URL: z.string().url(),
    NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string().min(1),
    NEXT_PUBLIC_APP_URL: z.string().url().optional(),
    NEXT_PUBLIC_SENTRY_DSN: z.string().url().optional(),
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: z.string().startsWith('pk_').optional(),
  },
  runtimeEnv: {
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
    BREVO_API_KEY: process.env.BREVO_API_KEY,
    DIGEST_FROM_EMAIL: process.env.DIGEST_FROM_EMAIL,
    APP_URL: process.env.APP_URL,
    CRON_SECRET: process.env.CRON_SECRET,
    SUPERADMIN_PASSWORD: process.env.SUPERADMIN_PASSWORD,
    SITE_PASSWORD: process.env.SITE_PASSWORD,
    DEEPL_API_KEY: process.env.DEEPL_API_KEY,
    SENTRY_DSN: process.env.SENTRY_DSN,
    SENTRY_ORG: process.env.SENTRY_ORG,
    SENTRY_PROJECT: process.env.SENTRY_PROJECT,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    STRIPE_PRICE_STARTER: process.env.STRIPE_PRICE_STARTER,
    STRIPE_PRICE_PROFESSIONAL: process.env.STRIPE_PRICE_PROFESSIONAL,
    STRIPE_PRICE_ENTERPRISE: process.env.STRIPE_PRICE_ENTERPRISE,
    STRIPE_PRICE_SOLO_MONTHLY: process.env.STRIPE_PRICE_SOLO_MONTHLY,
    STRIPE_PRICE_SOLO_YEARLY: process.env.STRIPE_PRICE_SOLO_YEARLY,
    STRIPE_PRICE_BUSINESS_MONTHLY: process.env.STRIPE_PRICE_BUSINESS_MONTHLY,
    STRIPE_PRICE_BUSINESS_YEARLY: process.env.STRIPE_PRICE_BUSINESS_YEARLY,
    STRIPE_PRICE_ENTERPRISE_MONTHLY: process.env.STRIPE_PRICE_ENTERPRISE_MONTHLY,
    STRIPE_PRICE_ENTERPRISE_YEARLY: process.env.STRIPE_PRICE_ENTERPRISE_YEARLY,
    STRIPE_PRICE_ADDON_PRINTER_MONTHLY: process.env.STRIPE_PRICE_ADDON_PRINTER_MONTHLY,
    STRIPE_PRICE_ADDON_PRINTER_YEARLY: process.env.STRIPE_PRICE_ADDON_PRINTER_YEARLY,
    STRIPE_PRICE_ADDON_PRINTER_HARDWARE: process.env.STRIPE_PRICE_ADDON_PRINTER_HARDWARE,
    STRIPE_PRICE_ADDON_AUDIT_EXPORT_MONTHLY: process.env.STRIPE_PRICE_ADDON_AUDIT_EXPORT_MONTHLY,
    STRIPE_PRICE_ADDON_AUDIT_EXPORT_YEARLY: process.env.STRIPE_PRICE_ADDON_AUDIT_EXPORT_YEARLY,
    STRIPE_PRICE_ADDON_CUSTOM_BRANDING_MONTHLY: process.env.STRIPE_PRICE_ADDON_CUSTOM_BRANDING_MONTHLY,
    STRIPE_PRICE_ADDON_CUSTOM_BRANDING_YEARLY: process.env.STRIPE_PRICE_ADDON_CUSTOM_BRANDING_YEARLY,
    STRIPE_PRICE_ADDON_EXTRA_LOCATION_MONTHLY: process.env.STRIPE_PRICE_ADDON_EXTRA_LOCATION_MONTHLY,
    STRIPE_PRICE_ADDON_EXTRA_LOCATION_YEARLY: process.env.STRIPE_PRICE_ADDON_EXTRA_LOCATION_YEARLY,
    STRIPE_PRICE_ADDON_BRIEFING_TRANSLATION_MONTHLY: process.env.STRIPE_PRICE_ADDON_BRIEFING_TRANSLATION_MONTHLY,
    STRIPE_PRICE_ADDON_BRIEFING_TRANSLATION_YEARLY: process.env.STRIPE_PRICE_ADDON_BRIEFING_TRANSLATION_YEARLY,
    STRIPE_PRICE_ADDON_PRIORITY_SUPPORT_MONTHLY: process.env.STRIPE_PRICE_ADDON_PRIORITY_SUPPORT_MONTHLY,
    STRIPE_PRICE_ADDON_PRIORITY_SUPPORT_YEARLY: process.env.STRIPE_PRICE_ADDON_PRIORITY_SUPPORT_YEARLY,
    NODE_ENV: process.env.NODE_ENV,
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
})
